mainSections = ["post"]
featuredImageField = "image"
rssFullContent = true
favicon = "/icons/logo.svg"

[footer]
since = 2024
customText = ""

[dateFormat]
# published = "Jan 02, 2006"
# lastUpdated = "Jan 02, 2006 15:04 MST"
published = "2006-01-02"
lastUpdated = "2006-01-02 15:04"

[sidebar]
emoji = "ğŸ¥"
subtitle = "é’æ˜¥æ°”è´¯é•¿è™¹"

[sidebar.avatar]
enabled = true
local = false
src = "https://images.pexels.com/users/avatars/99817764/stream-880.jpeg"

[article]
math = false
toc = true
readingTime = true

# å¯ä»¥æ·»åŠ è®¤è¯è„šæ³¨
[article.license]
enabled = false
default = ""

[comments]
enabled = false
provider = "disqus"

[comments.disqusjs]
shortname = ""
apiUrl = ""
apiKey = ""
admin = ""
adminLabel = ""

[comments.utterances]
repo = ""
issueTerm = "pathname"
label = ""

[comments.remark42]
host = ""
site = ""
locale = ""

[comments.vssue]
platform = ""
owner = ""
repo = ""
clientId = ""
clientSecret = ""
autoCreateIssue = false

[comments.waline]
serverURL = ""
lang = ""
visitor = ""
avatar = ""
emoji = ["https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo"]
requiredMeta = ["name", "email", "url"]
placeholder = ""

[comments.waline.locale]
admin = "Admin"

[comments.twikoo]
envId = ""
region = ""
path = ""
lang = ""

[comments.cactus]
defaultHomeserverUrl = "https://matrix.cactus.chat:8448"
serverName = "cactus.chat"
siteName = ""

[comments.giscus]
repo = ""
repoID = ""
category = ""
categoryID = ""
mapping = ""
lightTheme = ""
darkTheme = ""
reactionsEnabled = 1
emitMetadata = 0

[comments.gitalk]
owner = ""
admin = ""
repo = ""
clientID = ""
clientSecret = ""

[comments.cusdis]
host = ""
id = ""

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"
[widgets.homepage.params]
limit = 5

[[widgets.homepage]]
type = "categories"
[widgets.homepage.params]
limit = 10

[[widgets.homepage]]
type = "tag-cloud"
[widgets.homepage.params]
limit = 20

[[widgets.page]]
type = "toc"

[[widgets.page]]
type = "categories"
[widgets.page.params]
limit = 10

[[widgets.page]]
type = "tag-cloud"
[widgets.page.params]
limit = 15

[opengraph]
[opengraph.twitter]
site = ""
card = "summary_large_image"

[defaultImage]
[defaultImage.opengraph]
enabled = false
local = false
src = ""

[colorScheme]
toggle = true
default = "auto"

[imageProcessing]
[imageProcessing.cover]
enabled = true
[imageProcessing.content]
enabled = true
